title: LPC HATS -- NRP as a Resource for USCMS
subtitle: Intro to NRP, Running batch jobs, using Jupyterhub
length: 3 hours
date: 2026-08-10
indico_url: https://indico.cern.ch/event/1716267/
published: true
materials_branch: materials/cms-hats
lessons:
  - 0_setup
  - 1_intro
  - 2_kubernetes_basics
  - 3_prep
  - 4_hands_on
  - 5_cms_data
