title: LPC HATS -- NRP as a Resource for USCMS
subtitle: Intro to NRP, Running batch jobs, using Jupyterhub
length: 3 hours
# date: YYYY-MM-DD
published: true
materials_branch: materials/cms-hats
lessons:
  - 0_setup
  - 1_intro
