title: NAIRR Pilot Classroom Expansion Conferences
subtitle: Capacity and Community for Research Emerging Institutions with Large Computing Programs
length: 2 hours
order: 20
published: true
materials_branch: materials/cra-rel
lessons:
  - 1_intro
  - 2_inference
  - 3_agentic
  - 4_jupyterhub_helm
