apiVersion: v1
kind: Pod
metadata:
  name: tutorial-<username>-pod
  namespace: nrp-training-k8s
spec:
  tolerations:
  - key: nautilus.io/reservation
    operator: Equal
    value: nrp
    effect: NoSchedule
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: nrp-training
            operator: In
            values: ["true"]
  containers:
  - name: mypod
    image: amazon/aws-cli:2.31.36
    resources:
      limits:
        memory: 10Gi
        cpu: 4 
        ephemeral-storage: 100Gi
      requests:
        memory: 10Gi
        cpu: 4
        ephemeral-storage: 100Gi 
    command: ["/bin/bash", "-c"]
    args:
    - >- 
        yum -y install python3-pip;
        yum -y install wget;
        yum -y install gzip;
        yum -y install tar;
        pip3 install boto3;
        pip3 install torch;
        pip3 install torchvision;
        echo "Done with installs";
        sleep 3600s;
    volumeMounts:
    - name: scratch
      mountPath: /scratch
  volumes:
  - name: scratch
    emptyDir: {}
