apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jet-class-output-<username>
  namespace: us-cms
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
